// https://tezos.gitlab.io/whitedoc/michelson.html#full-grammar

export type MichelsonGrammarType =
  | 'nat'
  | 'int'
  | 'string'
  | 'bytes'
  | 'mutez'
  | 'bool'
  | 'key_hash'
  | 'timestamp'
  | 'address'
  | 'key'
  | 'unit'
  | 'signature'
  | 'option'
  | 'list'
  | 'set'
  | 'operation'
  | 'contract'
  | 'pair'
  | 'or'
  | 'lambda'
  | 'map'
  | 'big_map'
  | 'chain_id'
