export enum PolkadotStakingActionType {
    BOND_NOMINATE, 
    NOMINATE, 
    CANCEL_NOMINATION,
    CHANGE_NOMINATION,
    UNBOND, 
    REBOND, 
    BOND_EXTRA, 
    WITHDRAW_UNBONDED, 
    CHANGE_REWARD_DESTINATION, 
    CHANGE_CONTROLLER
}